CREATE TABLE `official_generated_documents` (
    `id` VARCHAR(191) NOT NULL,
    `verification_token` VARCHAR(64) NOT NULL,
    `document_kind` VARCHAR(64) NOT NULL,
    `source_id` VARCHAR(191) NOT NULL,
    `source_fingerprint` VARCHAR(64) NOT NULL,
    `version` INTEGER NOT NULL DEFAULT 1,
    `status` VARCHAR(32) NOT NULL DEFAULT 'current',
    `title` VARCHAR(255) NOT NULL,
    `document_number` VARCHAR(255) NULL,
    `subject_name` VARCHAR(255) NULL,
    `subject_identifier` VARCHAR(100) NULL,
    `issuer_name` VARCHAR(255) NULL,
    `issuer_role` VARCHAR(100) NULL,
    `file_path` VARCHAR(512) NOT NULL,
    `file_name` VARCHAR(255) NOT NULL,
    `file_size` INTEGER NOT NULL,
    `mime_type` VARCHAR(100) NOT NULL DEFAULT 'application/pdf',
    `file_hash` VARCHAR(64) NOT NULL,
    `issued_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `superseded_at` DATETIME(3) NULL,
    `revoked_at` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,
    UNIQUE INDEX `official_generated_documents_verification_token_key`(`verification_token`),
    UNIQUE INDEX `official_generated_documents_document_kind_source_id_version_key`(`document_kind`, `source_id`, `version`),
    INDEX `official_generated_documents_document_kind_source_id_status_idx`(`document_kind`, `source_id`, `status`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
